### ISSUE TITLE
Crash in Windows XP in script_unload()

### ISSUE THREAD

**Issue by dima-lur** [marc2k3/foo_jscript_panel#23] opened 2018-03-29 11:31 UTC
Version 2.1.0.2 Crash in Windows XP in script_unload()

**Comment by marc2k3** [comment] 2018-03-29 11:45
Works for me so you'll have to provide more details.

**Comment by dima-lur** [comment] 2018-03-29 11:51
Fresh install of Windows XP SP3 with no updates and no VC++ redistributabes installed. Foobar 1.4 beta 11 portable. Only JScript panel as 3d party component installed (v2.1.0.2). Open script editor, press Apply -> crash. Also when simply close foobar2000.

**Comment by dima-lur** [comment] 2018-03-29 11:57
I have installed VC++ 2017 Redistributable and no crash. Hm...

**Comment by marc2k3** [comment] 2018-03-29 12:13
Yep, I was able to reproduce that. I'll try and dig deeper but I suspect the problem is how the runtimes are bundled with foobar2000 itself.

**Comment by marc2k3** [comment] 2018-03-29 13:01
I've found the issue. It depends on a file named **concrt140.dll** which is installed by the C++ installer but not bundled with foobar2000 itself.

**Comment by marc2k3** [comment] 2018-03-29 13:15
I'm going to close this now as I've reported it to the foobar2000 developer and I'll update the requirements on the download/wiki page. Hopefully a future update will fix it.

**Closed by marc2k3** 2018-03-29 13:15 UTC

**Comment by marc2k3** [comment] 2018-05-04 18:34
@dima-lur , foobar2000 v1.4 Beta 12 now includes the required files.
