### ISSUE TITLE
foobar2000 crash v2.3.0

### ISSUE THREAD

**Issue by Wil-B** [marc2k3/foo_jscript_panel#47] opened 2019-10-04 11:11 UTC
JScript panel v2.3.0 caused a full foobar2000 crash (Crash location: Module: foo_jscript_panel). I then couldn't start foobar2000 until I removed JScript panel v2.3.0...

All I remember changing was the Selection Viewers setting in preferences.

I did eventually get it working, but I can't now reproduce by toggling that setting...

Hopefully crash reports point to the cause.

Report 1: original crash
Report 2: crash on trying to re-open foobar2000
[crash reports.zip](https://github.com/marc2k3/foo_jscript_panel/files/3690244/crash.reports.zip)

**Comment by marc2k3** [comment] 2019-10-04 12:02
Because I'm a buffoon, I didn't keep the files necessary for debugging when I compiled the DLL so I can't load the crash report in Visual Studio. I'll release a new version in a bit with a version bump and I'll make sure I'll keep the files in future.

As for being related to the Selection viewer change, there is no way to detect that inside the component. It just affects the results you get when using fb.GetSelection/fb.GetSelections - usually used inside the on_selection_changed callback. I tried hammering it with this bit of code but I can't make anything bad happen.

```js
function on_selection_changed() {
    var handle = fb.GetSelection();
    if (handle != null) { // fb.GetSelection could return null
        console.log(handle.Path);
    }
    
    var handles = fb.GetSelections(); // should always returns a valid handle list
    console.log(handles.Count);
    if (handles.Count > 0) {
        console.log(handles.Item(0).Path); // check the first item
    }
}
```

If you could let me know what script(s) you were using, maybe I could have a play around. You'll probably be using methods/callbacks that I don't use. Obviously if I change something knowingly, I always test what I can but in my day to day usage with my own scripts, I only touch a small subset of what is available.

**Comment by Wil-B** [comment] 2019-10-04 12:12
It was a test install and so it didn't have a lot in it.

Just test versions of biography, library tree & YouTube Track Manager with compatibility fixes for JSP breaking changes.

**Comment by marc2k3** [comment] 2019-10-04 12:28
Sorry for the inconvenience caused by this but I've just uploaded v2.3.0.1 which means I should be able to interpret crash reports in future...

https://github.com/marc2k3/foo_jscript_panel/releases

**Comment by marc2k3** [comment] 2019-10-04 14:16
Looking at the .txt files in the zip, it might be related to methods that return arrays? Could you test this as my collection is too small

```js
var items = fb.GetLibraryItems();

for (var i = 0; i < 10; i++) { //maybe increase this??
    items.OrderByFormat(fb.TitleFormat("$crc32(" + i + ")"), 1);
    items.OrderByRelativePath();
    
    var rp = items.GetLibraryRelativePaths().toArray();
    console.log("relative paths", rp.length);
    
    var metas = fb.TitleFormat("%artist% - %title% - %album%").EvalWithMetadbs(items).toArray();
    console.log("metas", metas.length);
    
    var arr = items.Convert().toArray();
    var new_items = fb.CreateHandleList();
    arr.forEach(function (item) {
        new_items.Add(item);
    });
    console.log("new_items", new_items.Count);
    new_items.Dispose();
}
```

**Comment by Wil-B** [comment] 2019-10-04 15:12
In fact the test install was only using a small monitored library of 3500.

Anyway I tested on that library + an artificial library of ~195,000 and put loop count up to 100. All completed OK:

metas 195776
new_items 195776
JScript Panel v2.3.0.1 (id:722496): initialised in 323789 ms

I'll test further over the next few days with normal scripts and let you know if it crashes again.

**Comment by Wil-B** [comment] 2019-10-07 12:05
Just to update you regarding the new version: v2.3.0.1. So far I have encounterd any issues.

**Comment by marc2k3** [comment] 2019-10-07 15:30
Urgh, I really hate bugs that can't be reproduced!! I'll close this for now but you can still comment/get it re-opened if anything happens in future.

**Closed by marc2k3** 2019-10-07 15:30 UTC
Labels: bug

**Comment by marc2k3** [comment] 2019-10-23 10:33
I think it's totally unrelated to this crash but I've discovered a new crash while using the editor. I've had to pull v2.3.x while I work on a fix. 😭
